// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv2D_conv2D.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv2D_conv2D::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv2D_conv2D::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> conv2D_conv2D::ap_ST_fsm_state1 = "1";
const sc_lv<7> conv2D_conv2D::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<7> conv2D_conv2D::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<7> conv2D_conv2D::ap_ST_fsm_pp0_stage2 = "1000";
const sc_lv<7> conv2D_conv2D::ap_ST_fsm_pp0_stage3 = "10000";
const sc_lv<7> conv2D_conv2D::ap_ST_fsm_pp0_stage4 = "100000";
const sc_lv<7> conv2D_conv2D::ap_ST_fsm_state15 = "1000000";
const sc_lv<32> conv2D_conv2D::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool conv2D_conv2D::ap_const_boolean_1 = true;
const sc_lv<32> conv2D_conv2D::ap_const_lv32_1 = "1";
const bool conv2D_conv2D::ap_const_boolean_0 = false;
const sc_lv<1> conv2D_conv2D::ap_const_lv1_0 = "0";
const sc_lv<32> conv2D_conv2D::ap_const_lv32_2 = "10";
const sc_lv<32> conv2D_conv2D::ap_const_lv32_3 = "11";
const sc_lv<32> conv2D_conv2D::ap_const_lv32_4 = "100";
const sc_lv<32> conv2D_conv2D::ap_const_lv32_5 = "101";
const sc_lv<1> conv2D_conv2D::ap_const_lv1_1 = "1";
const sc_lv<4> conv2D_conv2D::ap_const_lv4_0 = "0000";
const sc_lv<2> conv2D_conv2D::ap_const_lv2_0 = "00";
const sc_lv<64> conv2D_conv2D::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> conv2D_conv2D::ap_const_lv64_1 = "1";
const sc_lv<64> conv2D_conv2D::ap_const_lv64_2 = "10";
const sc_lv<64> conv2D_conv2D::ap_const_lv64_3 = "11";
const sc_lv<64> conv2D_conv2D::ap_const_lv64_4 = "100";
const sc_lv<64> conv2D_conv2D::ap_const_lv64_5 = "101";
const sc_lv<64> conv2D_conv2D::ap_const_lv64_6 = "110";
const sc_lv<64> conv2D_conv2D::ap_const_lv64_7 = "111";
const sc_lv<64> conv2D_conv2D::ap_const_lv64_8 = "1000";
const sc_lv<2> conv2D_conv2D::ap_const_lv2_1 = "1";
const sc_lv<4> conv2D_conv2D::ap_const_lv4_9 = "1001";
const sc_lv<4> conv2D_conv2D::ap_const_lv4_1 = "1";
const sc_lv<2> conv2D_conv2D::ap_const_lv2_3 = "11";
const sc_lv<2> conv2D_conv2D::ap_const_lv2_2 = "10";
const sc_lv<3> conv2D_conv2D::ap_const_lv3_2 = "10";
const sc_lv<32> conv2D_conv2D::ap_const_lv32_6 = "110";

conv2D_conv2D::conv2D_conv2D(sc_module_name name) : sc_module(name), mVcdFile(0) {
    conv2D_mul_32s_32s_32_4_1_U1 = new conv2D_conv2D_mul_32s_32s_32_4_1<1,4,32,32,32>("conv2D_mul_32s_32s_32_4_1_U1");
    conv2D_mul_32s_32s_32_4_1_U1->clk(ap_clk);
    conv2D_mul_32s_32s_32_4_1_U1->reset(ap_rst_reg);
    conv2D_mul_32s_32s_32_4_1_U1->din0(input_load_6_reg_762);
    conv2D_mul_32s_32s_32_4_1_U1->din1(kernel_load_6_reg_720);
    conv2D_mul_32s_32s_32_4_1_U1->ce(ap_var_for_const0);
    conv2D_mul_32s_32s_32_4_1_U1->dout(grp_fu_518_p2);
    conv2D_mul_32s_32s_32_4_1_U2 = new conv2D_conv2D_mul_32s_32s_32_4_1<1,4,32,32,32>("conv2D_mul_32s_32s_32_4_1_U2");
    conv2D_mul_32s_32s_32_4_1_U2->clk(ap_clk);
    conv2D_mul_32s_32s_32_4_1_U2->reset(ap_rst_reg);
    conv2D_mul_32s_32s_32_4_1_U2->din0(input_load_7_reg_767);
    conv2D_mul_32s_32s_32_4_1_U2->din1(kernel_load_7_reg_725);
    conv2D_mul_32s_32s_32_4_1_U2->ce(ap_var_for_const0);
    conv2D_mul_32s_32s_32_4_1_U2->dout(grp_fu_522_p2);
    conv2D_mul_32s_32s_32_4_1_U3 = new conv2D_conv2D_mul_32s_32s_32_4_1<1,4,32,32,32>("conv2D_mul_32s_32s_32_4_1_U3");
    conv2D_mul_32s_32s_32_4_1_U3->clk(ap_clk);
    conv2D_mul_32s_32s_32_4_1_U3->reset(ap_rst_reg);
    conv2D_mul_32s_32s_32_4_1_U3->din0(input_load_reg_782);
    conv2D_mul_32s_32s_32_4_1_U3->din1(kernel_load_reg_746);
    conv2D_mul_32s_32s_32_4_1_U3->ce(ap_var_for_const0);
    conv2D_mul_32s_32s_32_4_1_U3->dout(grp_fu_530_p2);
    conv2D_mul_32s_32s_32_4_1_U4 = new conv2D_conv2D_mul_32s_32s_32_4_1<1,4,32,32,32>("conv2D_mul_32s_32s_32_4_1_U4");
    conv2D_mul_32s_32s_32_4_1_U4->clk(ap_clk);
    conv2D_mul_32s_32s_32_4_1_U4->reset(ap_rst_reg);
    conv2D_mul_32s_32s_32_4_1_U4->din0(input_load_8_reg_817);
    conv2D_mul_32s_32s_32_4_1_U4->din1(kernel_load_8_reg_772);
    conv2D_mul_32s_32s_32_4_1_U4->ce(ap_var_for_const0);
    conv2D_mul_32s_32s_32_4_1_U4->dout(grp_fu_538_p2);
    conv2D_mul_32s_32s_32_4_1_U5 = new conv2D_conv2D_mul_32s_32s_32_4_1<1,4,32,32,32>("conv2D_mul_32s_32s_32_4_1_U5");
    conv2D_mul_32s_32s_32_4_1_U5->clk(ap_clk);
    conv2D_mul_32s_32s_32_4_1_U5->reset(ap_rst_reg);
    conv2D_mul_32s_32s_32_4_1_U5->din0(input_load_1_reg_832);
    conv2D_mul_32s_32s_32_4_1_U5->din1(kernel_load_1_reg_797);
    conv2D_mul_32s_32s_32_4_1_U5->ce(ap_var_for_const0);
    conv2D_mul_32s_32s_32_4_1_U5->dout(grp_fu_542_p2);
    conv2D_mul_32s_32s_32_4_1_U6 = new conv2D_conv2D_mul_32s_32s_32_4_1<1,4,32,32,32>("conv2D_mul_32s_32s_32_4_1_U6");
    conv2D_mul_32s_32s_32_4_1_U6->clk(ap_clk);
    conv2D_mul_32s_32s_32_4_1_U6->reset(ap_rst_reg);
    conv2D_mul_32s_32s_32_4_1_U6->din0(input_load_2_reg_837);
    conv2D_mul_32s_32s_32_4_1_U6->din1(kernel_load_2_reg_812);
    conv2D_mul_32s_32s_32_4_1_U6->ce(ap_var_for_const0);
    conv2D_mul_32s_32s_32_4_1_U6->dout(grp_fu_550_p2);
    conv2D_mul_32s_32s_32_4_1_U7 = new conv2D_conv2D_mul_32s_32s_32_4_1<1,4,32,32,32>("conv2D_mul_32s_32s_32_4_1_U7");
    conv2D_mul_32s_32s_32_4_1_U7->clk(ap_clk);
    conv2D_mul_32s_32s_32_4_1_U7->reset(ap_rst_reg);
    conv2D_mul_32s_32s_32_4_1_U7->din0(input_load_3_reg_857);
    conv2D_mul_32s_32s_32_4_1_U7->din1(kernel_load_3_reg_842);
    conv2D_mul_32s_32s_32_4_1_U7->ce(ap_var_for_const0);
    conv2D_mul_32s_32s_32_4_1_U7->dout(grp_fu_554_p2);
    conv2D_mul_32s_32s_32_4_1_U8 = new conv2D_conv2D_mul_32s_32s_32_4_1<1,4,32,32,32>("conv2D_mul_32s_32s_32_4_1_U8");
    conv2D_mul_32s_32s_32_4_1_U8->clk(ap_clk);
    conv2D_mul_32s_32s_32_4_1_U8->reset(ap_rst_reg);
    conv2D_mul_32s_32s_32_4_1_U8->din0(input_load_4_reg_862);
    conv2D_mul_32s_32s_32_4_1_U8->din1(kernel_load_4_reg_847);
    conv2D_mul_32s_32s_32_4_1_U8->ce(ap_var_for_const0);
    conv2D_mul_32s_32s_32_4_1_U8->dout(grp_fu_558_p2);
    conv2D_mul_32s_32s_32_4_1_U9 = new conv2D_conv2D_mul_32s_32s_32_4_1<1,4,32,32,32>("conv2D_mul_32s_32s_32_4_1_U9");
    conv2D_mul_32s_32s_32_4_1_U9->clk(ap_clk);
    conv2D_mul_32s_32s_32_4_1_U9->reset(ap_rst_reg);
    conv2D_mul_32s_32s_32_4_1_U9->din0(input_load_5_reg_872);
    conv2D_mul_32s_32s_32_4_1_U9->din1(kernel_load_5_reg_867);
    conv2D_mul_32s_32s_32_4_1_U9->ce(ap_var_for_const0);
    conv2D_mul_32s_32s_32_4_1_U9->dout(grp_fu_562_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_pp0_stage3);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);

    SC_METHOD(thread_ap_block_pp0_stage4);

    SC_METHOD(thread_ap_block_pp0_stage4_11001);

    SC_METHOD(thread_ap_block_pp0_stage4_subdone);

    SC_METHOD(thread_ap_block_state10_pp0_stage3_iter1);

    SC_METHOD(thread_ap_block_state11_pp0_stage4_iter1);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state13_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state14_pp0_stage2_iter2);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage4_iter0);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state8_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state9_pp0_stage2_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_flatten_fu_278_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_phi_mux_i_phi_fu_254_p4);
    sensitive << ( i_reg_250 );
    sensitive << ( exitcond_flatten_reg_651 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_mid2_reg_668 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten_phi_fu_243_p4);
    sensitive << ( indvar_flatten_reg_239 );
    sensitive << ( exitcond_flatten_reg_651 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_next_reg_655 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_j_phi_fu_265_p4);
    sensitive << ( j_reg_261 );
    sensitive << ( exitcond_flatten_reg_651 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( j_1_reg_704 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_exitcond_flatten_fu_278_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_243_p4 );

    SC_METHOD(thread_exitcond_fu_290_p2);
    sensitive << ( exitcond_flatten_fu_278_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_j_phi_fu_265_p4 );

    SC_METHOD(thread_i_1_fu_272_p2);
    sensitive << ( ap_phi_mux_i_phi_fu_254_p4 );

    SC_METHOD(thread_i_1_mid1_fu_312_p2);
    sensitive << ( ap_phi_mux_i_phi_fu_254_p4 );

    SC_METHOD(thread_indvar_flatten_next_fu_284_p2);
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_243_p4 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_13_cast_fu_365_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( tmp_20_cast_fu_460_p1 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( tmp_18_cast_fu_508_p1 );
    sensitive << ( ap_block_pp0_stage4 );
    sensitive << ( tmp_16_cast_fu_534_p1 );
    sensitive << ( tmp_19_cast_fu_546_p1 );

    SC_METHOD(thread_input_r_address1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( tmp_17_cast_fu_385_p1 );
    sensitive << ( tmp_11_cast_fu_434_p1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( tmp_15_cast_fu_494_p1 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( tmp_12_cast_fu_526_p1 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_input_r_ce1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );

    SC_METHOD(thread_j_1_fu_370_p2);
    sensitive << ( j_mid2_reg_660 );

    SC_METHOD(thread_j_cast_fu_423_p1);
    sensitive << ( j_mid2_reg_660 );

    SC_METHOD(thread_j_mid2_fu_296_p3);
    sensitive << ( ap_phi_mux_j_phi_fu_265_p4 );
    sensitive << ( exitcond_fu_290_p2 );

    SC_METHOD(thread_kernel_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_kernel_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_kernel_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );

    SC_METHOD(thread_kernel_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( tmp_14_cast_fu_592_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( tmp4_reg_937 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( tmp1_fu_596_p2 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( exitcond_flatten_reg_651_pp0_iter2_reg );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_p_shl1_cast_fu_475_p1);
    sensitive << ( tmp_2_fu_468_p3 );

    SC_METHOD(thread_p_shl3_cast1_fu_403_p1);
    sensitive << ( tmp_fu_396_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_407_p1);
    sensitive << ( tmp_fu_396_p3 );

    SC_METHOD(thread_p_shl_cast_fu_346_p1);
    sensitive << ( tmp_8_fu_339_p3 );

    SC_METHOD(thread_tmp1_fu_596_p2);
    sensitive << ( tmp2_reg_922 );
    sensitive << ( tmp3_reg_932 );

    SC_METHOD(thread_tmp2_fu_575_p2);
    sensitive << ( tmp_1_reg_887 );
    sensitive << ( tmp_1_0_1_reg_897 );

    SC_METHOD(thread_tmp3_fu_579_p2);
    sensitive << ( tmp_1_0_2_reg_902 );
    sensitive << ( tmp_1_1_reg_912 );

    SC_METHOD(thread_tmp4_fu_587_p2);
    sensitive << ( tmp6_reg_907 );
    sensitive << ( tmp5_fu_583_p2 );

    SC_METHOD(thread_tmp5_fu_583_p2);
    sensitive << ( tmp_1_1_1_reg_917 );
    sensitive << ( tmp_1_1_2_reg_927 );

    SC_METHOD(thread_tmp6_fu_570_p2);
    sensitive << ( tmp_1_2_reg_877 );
    sensitive << ( tmp7_fu_566_p2 );

    SC_METHOD(thread_tmp7_fu_566_p2);
    sensitive << ( tmp_1_2_1_reg_882 );
    sensitive << ( tmp_1_2_2_reg_892 );

    SC_METHOD(thread_tmp_10_fu_439_p2);
    sensitive << ( tmp_9_cast8_fu_426_p1 );
    sensitive << ( tmp_5_fu_417_p2 );

    SC_METHOD(thread_tmp_11_cast_fu_434_p1);
    sensitive << ( tmp_4_fu_429_p2 );

    SC_METHOD(thread_tmp_11_fu_490_p2);
    sensitive << ( tmp_9_0_1_cast_reg_709 );
    sensitive << ( tmp_3_reg_730 );

    SC_METHOD(thread_tmp_12_cast_fu_526_p1);
    sensitive << ( tmp_6_reg_777 );

    SC_METHOD(thread_tmp_12_fu_499_p2);
    sensitive << ( tmp_9_0_1_cast_reg_709 );
    sensitive << ( tmp_7_fu_479_p2 );

    SC_METHOD(thread_tmp_13_cast_fu_365_p1);
    sensitive << ( tmp_9_fu_359_p2 );

    SC_METHOD(thread_tmp_13_fu_379_p2);
    sensitive << ( tmp_s_fu_350_p2 );
    sensitive << ( tmp_9_0_1_cast_fu_375_p1 );

    SC_METHOD(thread_tmp_14_cast_fu_592_p1);
    sensitive << ( tmp_10_reg_741_pp0_iter1_reg );

    SC_METHOD(thread_tmp_14_fu_504_p2);
    sensitive << ( tmp_3_reg_730 );
    sensitive << ( tmp_9_0_2_cast_reg_751 );

    SC_METHOD(thread_tmp_15_cast_fu_494_p1);
    sensitive << ( tmp_11_fu_490_p2 );

    SC_METHOD(thread_tmp_15_fu_513_p2);
    sensitive << ( tmp_9_0_2_cast_reg_751 );
    sensitive << ( tmp_7_fu_479_p2 );

    SC_METHOD(thread_tmp_16_cast_fu_534_p1);
    sensitive << ( tmp_12_reg_792 );

    SC_METHOD(thread_tmp_16_fu_455_p2);
    sensitive << ( tmp_s_reg_688 );
    sensitive << ( tmp_9_0_2_cast_fu_451_p1 );

    SC_METHOD(thread_tmp_17_cast_fu_385_p1);
    sensitive << ( tmp_13_fu_379_p2 );

    SC_METHOD(thread_tmp_18_cast_fu_508_p1);
    sensitive << ( tmp_14_fu_504_p2 );

    SC_METHOD(thread_tmp_19_cast_fu_546_p1);
    sensitive << ( tmp_15_reg_807 );

    SC_METHOD(thread_tmp_20_cast_fu_460_p1);
    sensitive << ( tmp_16_fu_455_p2 );

    SC_METHOD(thread_tmp_2_fu_468_p3);
    sensitive << ( tmp_5_1_mid2_reg_676 );

    SC_METHOD(thread_tmp_3_fu_411_p2);
    sensitive << ( p_shl3_cast1_fu_403_p1 );
    sensitive << ( tmp_mid2_cast1_fu_390_p1 );

    SC_METHOD(thread_tmp_4_fu_429_p2);
    sensitive << ( tmp_9_cast_reg_693 );
    sensitive << ( tmp_3_fu_411_p2 );

    SC_METHOD(thread_tmp_5_1_mid2_cast9_fu_465_p1);
    sensitive << ( tmp_5_1_mid2_reg_676 );

    SC_METHOD(thread_tmp_5_1_mid2_fu_318_p3);
    sensitive << ( exitcond_fu_290_p2 );
    sensitive << ( i_1_fu_272_p2 );
    sensitive << ( i_1_mid1_fu_312_p2 );

    SC_METHOD(thread_tmp_5_2_mid2_cast_fu_336_p1);
    sensitive << ( tmp_5_2_mid2_v_reg_682 );

    SC_METHOD(thread_tmp_5_2_mid2_v_fu_330_p2);
    sensitive << ( tmp_5_2_mid2_v_v_fu_326_p1 );

    SC_METHOD(thread_tmp_5_2_mid2_v_v_fu_326_p1);
    sensitive << ( tmp_mid2_fu_304_p3 );

    SC_METHOD(thread_tmp_5_fu_417_p2);
    sensitive << ( p_shl3_cast_fu_407_p1 );
    sensitive << ( tmp_mid2_cast_fu_393_p1 );

    SC_METHOD(thread_tmp_6_fu_485_p2);
    sensitive << ( tmp_9_cast_reg_693 );
    sensitive << ( tmp_7_fu_479_p2 );

    SC_METHOD(thread_tmp_7_fu_479_p2);
    sensitive << ( p_shl1_cast_fu_475_p1 );
    sensitive << ( tmp_5_1_mid2_cast9_fu_465_p1 );

    SC_METHOD(thread_tmp_8_0_2_fu_445_p2);
    sensitive << ( j_cast_fu_423_p1 );

    SC_METHOD(thread_tmp_8_fu_339_p3);
    sensitive << ( tmp_5_2_mid2_v_reg_682 );

    SC_METHOD(thread_tmp_9_0_1_cast_fu_375_p1);
    sensitive << ( j_1_fu_370_p2 );

    SC_METHOD(thread_tmp_9_0_2_cast_fu_451_p1);
    sensitive << ( tmp_8_0_2_fu_445_p2 );

    SC_METHOD(thread_tmp_9_cast8_fu_426_p1);
    sensitive << ( j_mid2_reg_660 );

    SC_METHOD(thread_tmp_9_cast_fu_356_p1);
    sensitive << ( j_mid2_reg_660 );

    SC_METHOD(thread_tmp_9_fu_359_p2);
    sensitive << ( tmp_s_fu_350_p2 );
    sensitive << ( tmp_9_cast_fu_356_p1 );

    SC_METHOD(thread_tmp_fu_396_p3);
    sensitive << ( tmp_mid2_reg_668 );

    SC_METHOD(thread_tmp_mid2_cast1_fu_390_p1);
    sensitive << ( tmp_mid2_reg_668 );

    SC_METHOD(thread_tmp_mid2_cast_fu_393_p1);
    sensitive << ( tmp_mid2_reg_668 );

    SC_METHOD(thread_tmp_mid2_fu_304_p3);
    sensitive << ( ap_phi_mux_i_phi_fu_254_p4 );
    sensitive << ( exitcond_fu_290_p2 );
    sensitive << ( i_1_fu_272_p2 );

    SC_METHOD(thread_tmp_s_fu_350_p2);
    sensitive << ( p_shl_cast_fu_346_p1 );
    sensitive << ( tmp_5_2_mid2_cast_fu_336_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond_flatten_fu_278_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage4_subdone );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp0_stage3_subdone );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_rst_reg_2 = SC_LOGIC_1;
    ap_rst_reg_1 = SC_LOGIC_1;
    ap_rst_reg = SC_LOGIC_1;
    ap_CS_fsm = "0000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv2D_conv2D_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, input_r_address1, "(port)input_r_address1");
    sc_trace(mVcdFile, input_r_ce1, "(port)input_r_ce1");
    sc_trace(mVcdFile, input_r_q1, "(port)input_r_q1");
    sc_trace(mVcdFile, kernel_address0, "(port)kernel_address0");
    sc_trace(mVcdFile, kernel_ce0, "(port)kernel_ce0");
    sc_trace(mVcdFile, kernel_q0, "(port)kernel_q0");
    sc_trace(mVcdFile, kernel_address1, "(port)kernel_address1");
    sc_trace(mVcdFile, kernel_ce1, "(port)kernel_ce1");
    sc_trace(mVcdFile, kernel_q1, "(port)kernel_q1");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_reg_2, "ap_rst_reg_2");
    sc_trace(mVcdFile, ap_rst_reg_1, "ap_rst_reg_1");
    sc_trace(mVcdFile, ap_rst_reg, "ap_rst_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten_reg_239, "indvar_flatten_reg_239");
    sc_trace(mVcdFile, i_reg_250, "i_reg_250");
    sc_trace(mVcdFile, j_reg_261, "j_reg_261");
    sc_trace(mVcdFile, exitcond_flatten_fu_278_p2, "exitcond_flatten_fu_278_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_651, "exitcond_flatten_reg_651");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter1, "ap_block_state7_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter2, "ap_block_state12_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_flatten_reg_651_pp0_iter1_reg, "exitcond_flatten_reg_651_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_651_pp0_iter2_reg, "exitcond_flatten_reg_651_pp0_iter2_reg");
    sc_trace(mVcdFile, indvar_flatten_next_fu_284_p2, "indvar_flatten_next_fu_284_p2");
    sc_trace(mVcdFile, indvar_flatten_next_reg_655, "indvar_flatten_next_reg_655");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, j_mid2_fu_296_p3, "j_mid2_fu_296_p3");
    sc_trace(mVcdFile, j_mid2_reg_660, "j_mid2_reg_660");
    sc_trace(mVcdFile, tmp_mid2_fu_304_p3, "tmp_mid2_fu_304_p3");
    sc_trace(mVcdFile, tmp_mid2_reg_668, "tmp_mid2_reg_668");
    sc_trace(mVcdFile, tmp_5_1_mid2_fu_318_p3, "tmp_5_1_mid2_fu_318_p3");
    sc_trace(mVcdFile, tmp_5_1_mid2_reg_676, "tmp_5_1_mid2_reg_676");
    sc_trace(mVcdFile, tmp_5_2_mid2_v_fu_330_p2, "tmp_5_2_mid2_v_fu_330_p2");
    sc_trace(mVcdFile, tmp_5_2_mid2_v_reg_682, "tmp_5_2_mid2_v_reg_682");
    sc_trace(mVcdFile, tmp_s_fu_350_p2, "tmp_s_fu_350_p2");
    sc_trace(mVcdFile, tmp_s_reg_688, "tmp_s_reg_688");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage1_iter1, "ap_block_state8_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage1_iter2, "ap_block_state13_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, tmp_9_cast_fu_356_p1, "tmp_9_cast_fu_356_p1");
    sc_trace(mVcdFile, tmp_9_cast_reg_693, "tmp_9_cast_reg_693");
    sc_trace(mVcdFile, j_1_fu_370_p2, "j_1_fu_370_p2");
    sc_trace(mVcdFile, j_1_reg_704, "j_1_reg_704");
    sc_trace(mVcdFile, tmp_9_0_1_cast_fu_375_p1, "tmp_9_0_1_cast_fu_375_p1");
    sc_trace(mVcdFile, tmp_9_0_1_cast_reg_709, "tmp_9_0_1_cast_reg_709");
    sc_trace(mVcdFile, kernel_load_6_reg_720, "kernel_load_6_reg_720");
    sc_trace(mVcdFile, kernel_load_7_reg_725, "kernel_load_7_reg_725");
    sc_trace(mVcdFile, tmp_3_fu_411_p2, "tmp_3_fu_411_p2");
    sc_trace(mVcdFile, tmp_3_reg_730, "tmp_3_reg_730");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage2_iter0, "ap_block_state4_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage2_iter1, "ap_block_state9_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage2_iter2, "ap_block_state14_pp0_stage2_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, tmp_10_fu_439_p2, "tmp_10_fu_439_p2");
    sc_trace(mVcdFile, tmp_10_reg_741, "tmp_10_reg_741");
    sc_trace(mVcdFile, tmp_10_reg_741_pp0_iter1_reg, "tmp_10_reg_741_pp0_iter1_reg");
    sc_trace(mVcdFile, kernel_load_reg_746, "kernel_load_reg_746");
    sc_trace(mVcdFile, tmp_9_0_2_cast_fu_451_p1, "tmp_9_0_2_cast_fu_451_p1");
    sc_trace(mVcdFile, tmp_9_0_2_cast_reg_751, "tmp_9_0_2_cast_reg_751");
    sc_trace(mVcdFile, input_load_6_reg_762, "input_load_6_reg_762");
    sc_trace(mVcdFile, input_load_7_reg_767, "input_load_7_reg_767");
    sc_trace(mVcdFile, kernel_load_8_reg_772, "kernel_load_8_reg_772");
    sc_trace(mVcdFile, tmp_6_fu_485_p2, "tmp_6_fu_485_p2");
    sc_trace(mVcdFile, tmp_6_reg_777, "tmp_6_reg_777");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage3_iter0, "ap_block_state5_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage3_iter1, "ap_block_state10_pp0_stage3_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, input_load_reg_782, "input_load_reg_782");
    sc_trace(mVcdFile, tmp_12_fu_499_p2, "tmp_12_fu_499_p2");
    sc_trace(mVcdFile, tmp_12_reg_792, "tmp_12_reg_792");
    sc_trace(mVcdFile, kernel_load_1_reg_797, "kernel_load_1_reg_797");
    sc_trace(mVcdFile, tmp_15_fu_513_p2, "tmp_15_fu_513_p2");
    sc_trace(mVcdFile, tmp_15_reg_807, "tmp_15_reg_807");
    sc_trace(mVcdFile, kernel_load_2_reg_812, "kernel_load_2_reg_812");
    sc_trace(mVcdFile, input_load_8_reg_817, "input_load_8_reg_817");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage4, "ap_CS_fsm_pp0_stage4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage4_iter0, "ap_block_state6_pp0_stage4_iter0");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage4_iter1, "ap_block_state11_pp0_stage4_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage4_11001, "ap_block_pp0_stage4_11001");
    sc_trace(mVcdFile, input_load_1_reg_832, "input_load_1_reg_832");
    sc_trace(mVcdFile, input_load_2_reg_837, "input_load_2_reg_837");
    sc_trace(mVcdFile, kernel_load_3_reg_842, "kernel_load_3_reg_842");
    sc_trace(mVcdFile, kernel_load_4_reg_847, "kernel_load_4_reg_847");
    sc_trace(mVcdFile, input_load_3_reg_857, "input_load_3_reg_857");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, input_load_4_reg_862, "input_load_4_reg_862");
    sc_trace(mVcdFile, kernel_load_5_reg_867, "kernel_load_5_reg_867");
    sc_trace(mVcdFile, input_load_5_reg_872, "input_load_5_reg_872");
    sc_trace(mVcdFile, grp_fu_518_p2, "grp_fu_518_p2");
    sc_trace(mVcdFile, tmp_1_2_reg_877, "tmp_1_2_reg_877");
    sc_trace(mVcdFile, grp_fu_522_p2, "grp_fu_522_p2");
    sc_trace(mVcdFile, tmp_1_2_1_reg_882, "tmp_1_2_1_reg_882");
    sc_trace(mVcdFile, grp_fu_530_p2, "grp_fu_530_p2");
    sc_trace(mVcdFile, tmp_1_reg_887, "tmp_1_reg_887");
    sc_trace(mVcdFile, grp_fu_538_p2, "grp_fu_538_p2");
    sc_trace(mVcdFile, tmp_1_2_2_reg_892, "tmp_1_2_2_reg_892");
    sc_trace(mVcdFile, grp_fu_542_p2, "grp_fu_542_p2");
    sc_trace(mVcdFile, tmp_1_0_1_reg_897, "tmp_1_0_1_reg_897");
    sc_trace(mVcdFile, grp_fu_550_p2, "grp_fu_550_p2");
    sc_trace(mVcdFile, tmp_1_0_2_reg_902, "tmp_1_0_2_reg_902");
    sc_trace(mVcdFile, tmp6_fu_570_p2, "tmp6_fu_570_p2");
    sc_trace(mVcdFile, tmp6_reg_907, "tmp6_reg_907");
    sc_trace(mVcdFile, grp_fu_554_p2, "grp_fu_554_p2");
    sc_trace(mVcdFile, tmp_1_1_reg_912, "tmp_1_1_reg_912");
    sc_trace(mVcdFile, grp_fu_558_p2, "grp_fu_558_p2");
    sc_trace(mVcdFile, tmp_1_1_1_reg_917, "tmp_1_1_1_reg_917");
    sc_trace(mVcdFile, tmp2_fu_575_p2, "tmp2_fu_575_p2");
    sc_trace(mVcdFile, tmp2_reg_922, "tmp2_reg_922");
    sc_trace(mVcdFile, grp_fu_562_p2, "grp_fu_562_p2");
    sc_trace(mVcdFile, tmp_1_1_2_reg_927, "tmp_1_1_2_reg_927");
    sc_trace(mVcdFile, tmp3_fu_579_p2, "tmp3_fu_579_p2");
    sc_trace(mVcdFile, tmp3_reg_932, "tmp3_reg_932");
    sc_trace(mVcdFile, tmp4_fu_587_p2, "tmp4_fu_587_p2");
    sc_trace(mVcdFile, tmp4_reg_937, "tmp4_reg_937");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage4_subdone, "ap_block_pp0_stage4_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten_phi_fu_243_p4, "ap_phi_mux_indvar_flatten_phi_fu_243_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_i_phi_fu_254_p4, "ap_phi_mux_i_phi_fu_254_p4");
    sc_trace(mVcdFile, ap_phi_mux_j_phi_fu_265_p4, "ap_phi_mux_j_phi_fu_265_p4");
    sc_trace(mVcdFile, tmp_13_cast_fu_365_p1, "tmp_13_cast_fu_365_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, tmp_17_cast_fu_385_p1, "tmp_17_cast_fu_385_p1");
    sc_trace(mVcdFile, tmp_11_cast_fu_434_p1, "tmp_11_cast_fu_434_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, tmp_20_cast_fu_460_p1, "tmp_20_cast_fu_460_p1");
    sc_trace(mVcdFile, tmp_15_cast_fu_494_p1, "tmp_15_cast_fu_494_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage3, "ap_block_pp0_stage3");
    sc_trace(mVcdFile, tmp_18_cast_fu_508_p1, "tmp_18_cast_fu_508_p1");
    sc_trace(mVcdFile, tmp_12_cast_fu_526_p1, "tmp_12_cast_fu_526_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage4, "ap_block_pp0_stage4");
    sc_trace(mVcdFile, tmp_16_cast_fu_534_p1, "tmp_16_cast_fu_534_p1");
    sc_trace(mVcdFile, tmp_19_cast_fu_546_p1, "tmp_19_cast_fu_546_p1");
    sc_trace(mVcdFile, tmp_14_cast_fu_592_p1, "tmp_14_cast_fu_592_p1");
    sc_trace(mVcdFile, exitcond_fu_290_p2, "exitcond_fu_290_p2");
    sc_trace(mVcdFile, i_1_fu_272_p2, "i_1_fu_272_p2");
    sc_trace(mVcdFile, i_1_mid1_fu_312_p2, "i_1_mid1_fu_312_p2");
    sc_trace(mVcdFile, tmp_5_2_mid2_v_v_fu_326_p1, "tmp_5_2_mid2_v_v_fu_326_p1");
    sc_trace(mVcdFile, tmp_8_fu_339_p3, "tmp_8_fu_339_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_346_p1, "p_shl_cast_fu_346_p1");
    sc_trace(mVcdFile, tmp_5_2_mid2_cast_fu_336_p1, "tmp_5_2_mid2_cast_fu_336_p1");
    sc_trace(mVcdFile, tmp_9_fu_359_p2, "tmp_9_fu_359_p2");
    sc_trace(mVcdFile, tmp_13_fu_379_p2, "tmp_13_fu_379_p2");
    sc_trace(mVcdFile, tmp_fu_396_p3, "tmp_fu_396_p3");
    sc_trace(mVcdFile, p_shl3_cast1_fu_403_p1, "p_shl3_cast1_fu_403_p1");
    sc_trace(mVcdFile, tmp_mid2_cast1_fu_390_p1, "tmp_mid2_cast1_fu_390_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_407_p1, "p_shl3_cast_fu_407_p1");
    sc_trace(mVcdFile, tmp_mid2_cast_fu_393_p1, "tmp_mid2_cast_fu_393_p1");
    sc_trace(mVcdFile, tmp_4_fu_429_p2, "tmp_4_fu_429_p2");
    sc_trace(mVcdFile, tmp_9_cast8_fu_426_p1, "tmp_9_cast8_fu_426_p1");
    sc_trace(mVcdFile, tmp_5_fu_417_p2, "tmp_5_fu_417_p2");
    sc_trace(mVcdFile, j_cast_fu_423_p1, "j_cast_fu_423_p1");
    sc_trace(mVcdFile, tmp_8_0_2_fu_445_p2, "tmp_8_0_2_fu_445_p2");
    sc_trace(mVcdFile, tmp_16_fu_455_p2, "tmp_16_fu_455_p2");
    sc_trace(mVcdFile, tmp_2_fu_468_p3, "tmp_2_fu_468_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_475_p1, "p_shl1_cast_fu_475_p1");
    sc_trace(mVcdFile, tmp_5_1_mid2_cast9_fu_465_p1, "tmp_5_1_mid2_cast9_fu_465_p1");
    sc_trace(mVcdFile, tmp_7_fu_479_p2, "tmp_7_fu_479_p2");
    sc_trace(mVcdFile, tmp_11_fu_490_p2, "tmp_11_fu_490_p2");
    sc_trace(mVcdFile, tmp_14_fu_504_p2, "tmp_14_fu_504_p2");
    sc_trace(mVcdFile, tmp7_fu_566_p2, "tmp7_fu_566_p2");
    sc_trace(mVcdFile, tmp5_fu_583_p2, "tmp5_fu_583_p2");
    sc_trace(mVcdFile, tmp1_fu_596_p2, "tmp1_fu_596_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
    mHdltvinHandle.open("conv2D_conv2D.hdltvin.dat");
    mHdltvoutHandle.open("conv2D_conv2D.hdltvout.dat");
}

conv2D_conv2D::~conv2D_conv2D() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete conv2D_mul_32s_32s_32_4_1_U1;
    delete conv2D_mul_32s_32s_32_4_1_U2;
    delete conv2D_mul_32s_32s_32_4_1_U3;
    delete conv2D_mul_32s_32s_32_4_1_U4;
    delete conv2D_mul_32s_32s_32_4_1_U5;
    delete conv2D_mul_32s_32s_32_4_1_U6;
    delete conv2D_mul_32s_32s_32_4_1_U7;
    delete conv2D_mul_32s_32s_32_4_1_U8;
    delete conv2D_mul_32s_32s_32_4_1_U9;
}

void conv2D_conv2D::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void conv2D_conv2D::thread_ap_clk_no_reset_() {
    if ( ap_rst_reg.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_reg.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_reg.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst_reg.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    ap_rst_reg = ap_rst_reg_1.read();
    ap_rst_reg_1 = ap_rst_reg_2.read();
    ap_rst_reg_2 = ap_rst.read();
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i_reg_250 = tmp_mid2_reg_668.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_250 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten_reg_239 = indvar_flatten_next_reg_655.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_239 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        j_reg_261 = j_1_reg_704.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_reg_261 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten_reg_651 = exitcond_flatten_fu_278_p2.read();
        exitcond_flatten_reg_651_pp0_iter1_reg = exitcond_flatten_reg_651.read();
        exitcond_flatten_reg_651_pp0_iter2_reg = exitcond_flatten_reg_651_pp0_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        indvar_flatten_next_reg_655 = indvar_flatten_next_fu_284_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0))) {
        input_load_1_reg_832 = input_r_q1.read();
        input_load_2_reg_837 = input_r_q0.read();
        kernel_load_3_reg_842 = kernel_q0.read();
        kernel_load_4_reg_847 = kernel_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        input_load_3_reg_857 = input_r_q1.read();
        input_load_4_reg_862 = input_r_q0.read();
        kernel_load_5_reg_867 = kernel_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_651_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        input_load_5_reg_872 = input_r_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        input_load_6_reg_762 = input_r_q0.read();
        input_load_7_reg_767 = input_r_q1.read();
        kernel_load_8_reg_772 = kernel_q1.read();
        kernel_load_reg_746 = kernel_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        input_load_8_reg_817 = input_r_q0.read();
        input_load_reg_782 = input_r_q1.read();
        kernel_load_1_reg_797 = kernel_q0.read();
        kernel_load_2_reg_812 = kernel_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0))) {
        j_1_reg_704 = j_1_fu_370_p2.read();
        kernel_load_6_reg_720 = kernel_q0.read();
        kernel_load_7_reg_725 = kernel_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_278_p2.read(), ap_const_lv1_0))) {
        j_mid2_reg_660 = j_mid2_fu_296_p3.read();
        tmp_5_1_mid2_reg_676 = tmp_5_1_mid2_fu_318_p3.read();
        tmp_5_2_mid2_v_reg_682 = tmp_5_2_mid2_v_fu_330_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_651_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        tmp2_reg_922 = tmp2_fu_575_p2.read();
        tmp_1_1_1_reg_917 = grp_fu_558_p2.read();
        tmp_1_1_reg_912 = grp_fu_554_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_651_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        tmp3_reg_932 = tmp3_fu_579_p2.read();
        tmp_1_1_2_reg_927 = grp_fu_562_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_651_pp0_iter2_reg.read(), ap_const_lv1_0))) {
        tmp4_reg_937 = tmp4_fu_587_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_651_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        tmp6_reg_907 = tmp6_fu_570_p2.read();
        tmp_1_0_1_reg_897 = grp_fu_542_p2.read();
        tmp_1_0_2_reg_902 = grp_fu_550_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        tmp_10_reg_741 = tmp_10_fu_439_p2.read();
        tmp_3_reg_730 = tmp_3_fu_411_p2.read();
        tmp_9_0_2_cast_reg_751 = tmp_9_0_2_cast_fu_451_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        tmp_10_reg_741_pp0_iter1_reg = tmp_10_reg_741.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        tmp_12_reg_792 = tmp_12_fu_499_p2.read();
        tmp_15_reg_807 = tmp_15_fu_513_p2.read();
        tmp_6_reg_777 = tmp_6_fu_485_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_651_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        tmp_1_2_1_reg_882 = grp_fu_522_p2.read();
        tmp_1_2_reg_877 = grp_fu_518_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_651_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        tmp_1_2_2_reg_892 = grp_fu_538_p2.read();
        tmp_1_reg_887 = grp_fu_530_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0))) {
        tmp_9_0_1_cast_reg_709 = tmp_9_0_1_cast_fu_375_p1.read();
        tmp_9_cast_reg_693 = tmp_9_cast_fu_356_p1.read();
        tmp_s_reg_688 = tmp_s_fu_350_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_278_p2.read(), ap_const_lv1_0))) {
        tmp_mid2_reg_668 = tmp_mid2_fu_304_p3.read();
    }
}

void conv2D_conv2D::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void conv2D_conv2D::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void conv2D_conv2D::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[3];
}

void conv2D_conv2D::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[4];
}

void conv2D_conv2D::thread_ap_CS_fsm_pp0_stage4() {
    ap_CS_fsm_pp0_stage4 = ap_CS_fsm.read()[5];
}

void conv2D_conv2D::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv2D_conv2D::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[6];
}

void conv2D_conv2D::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage3() {
    ap_block_pp0_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage4() {
    ap_block_pp0_stage4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage4_11001() {
    ap_block_pp0_stage4_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_pp0_stage4_subdone() {
    ap_block_pp0_stage4_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state10_pp0_stage3_iter1() {
    ap_block_state10_pp0_stage3_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state11_pp0_stage4_iter1() {
    ap_block_state11_pp0_stage4_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state12_pp0_stage0_iter2() {
    ap_block_state12_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state13_pp0_stage1_iter2() {
    ap_block_state13_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state14_pp0_stage2_iter2() {
    ap_block_state14_pp0_stage2_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state4_pp0_stage2_iter0() {
    ap_block_state4_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state5_pp0_stage3_iter0() {
    ap_block_state5_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state6_pp0_stage4_iter0() {
    ap_block_state6_pp0_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state7_pp0_stage0_iter1() {
    ap_block_state7_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state8_pp0_stage1_iter1() {
    ap_block_state8_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_block_state9_pp0_stage2_iter1() {
    ap_block_state9_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv2D_conv2D::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_flatten_fu_278_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void conv2D_conv2D::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_ap_phi_mux_i_phi_fu_254_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_phi_fu_254_p4 = tmp_mid2_reg_668.read();
    } else {
        ap_phi_mux_i_phi_fu_254_p4 = i_reg_250.read();
    }
}

void conv2D_conv2D::thread_ap_phi_mux_indvar_flatten_phi_fu_243_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten_phi_fu_243_p4 = indvar_flatten_next_reg_655.read();
    } else {
        ap_phi_mux_indvar_flatten_phi_fu_243_p4 = indvar_flatten_reg_239.read();
    }
}

void conv2D_conv2D::thread_ap_phi_mux_j_phi_fu_265_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_651.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_phi_fu_265_p4 = j_1_reg_704.read();
    } else {
        ap_phi_mux_j_phi_fu_265_p4 = j_reg_261.read();
    }
}

void conv2D_conv2D::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_exitcond_flatten_fu_278_p2() {
    exitcond_flatten_fu_278_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_243_p4.read().is_01() || !ap_const_lv4_9.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten_phi_fu_243_p4.read() == ap_const_lv4_9);
}

void conv2D_conv2D::thread_exitcond_fu_290_p2() {
    exitcond_fu_290_p2 = (!ap_phi_mux_j_phi_fu_265_p4.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_j_phi_fu_265_p4.read() == ap_const_lv2_3);
}

void conv2D_conv2D::thread_i_1_fu_272_p2() {
    i_1_fu_272_p2 = (!ap_phi_mux_i_phi_fu_254_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(ap_phi_mux_i_phi_fu_254_p4.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2D_conv2D::thread_i_1_mid1_fu_312_p2() {
    i_1_mid1_fu_312_p2 = (ap_phi_mux_i_phi_fu_254_p4.read() ^ ap_const_lv2_2);
}

void conv2D_conv2D::thread_indvar_flatten_next_fu_284_p2() {
    indvar_flatten_next_fu_284_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_243_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ap_phi_mux_indvar_flatten_phi_fu_243_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv2D_conv2D::thread_input_r_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        input_r_address0 =  (sc_lv<5>) (tmp_19_cast_fu_546_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
        input_r_address0 =  (sc_lv<5>) (tmp_16_cast_fu_534_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        input_r_address0 =  (sc_lv<5>) (tmp_18_cast_fu_508_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        input_r_address0 =  (sc_lv<5>) (tmp_20_cast_fu_460_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        input_r_address0 =  (sc_lv<5>) (tmp_13_cast_fu_365_p1.read());
    } else {
        input_r_address0 = "XXXXX";
    }
}

void conv2D_conv2D::thread_input_r_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            input_r_address1 =  (sc_lv<5>) (tmp_12_cast_fu_526_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            input_r_address1 =  (sc_lv<5>) (tmp_15_cast_fu_494_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            input_r_address1 =  (sc_lv<5>) (tmp_11_cast_fu_434_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            input_r_address1 =  (sc_lv<5>) (tmp_17_cast_fu_385_p1.read());
        } else {
            input_r_address1 = "XXXXX";
        }
    } else {
        input_r_address1 = "XXXXX";
    }
}

void conv2D_conv2D::thread_input_r_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_input_r_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0)))) {
        input_r_ce1 = ap_const_logic_1;
    } else {
        input_r_ce1 = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_j_1_fu_370_p2() {
    j_1_fu_370_p2 = (!j_mid2_reg_660.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_mid2_reg_660.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2D_conv2D::thread_j_cast_fu_423_p1() {
    j_cast_fu_423_p1 = esl_zext<3,2>(j_mid2_reg_660.read());
}

void conv2D_conv2D::thread_j_mid2_fu_296_p3() {
    j_mid2_fu_296_p3 = (!exitcond_fu_290_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_fu_290_p2.read()[0].to_bool())? ap_const_lv2_0: ap_phi_mux_j_phi_fu_265_p4.read());
}

void conv2D_conv2D::thread_kernel_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            kernel_address0 =  (sc_lv<4>) (ap_const_lv64_5);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            kernel_address0 =  (sc_lv<4>) (ap_const_lv64_3);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            kernel_address0 =  (sc_lv<4>) (ap_const_lv64_1);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            kernel_address0 =  (sc_lv<4>) (ap_const_lv64_0);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            kernel_address0 =  (sc_lv<4>) (ap_const_lv64_6);
        } else {
            kernel_address0 =  (sc_lv<4>) ("XXXX");
        }
    } else {
        kernel_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void conv2D_conv2D::thread_kernel_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            kernel_address1 =  (sc_lv<4>) (ap_const_lv64_4);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            kernel_address1 =  (sc_lv<4>) (ap_const_lv64_2);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            kernel_address1 =  (sc_lv<4>) (ap_const_lv64_8);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            kernel_address1 =  (sc_lv<4>) (ap_const_lv64_7);
        } else {
            kernel_address1 =  (sc_lv<4>) ("XXXX");
        }
    } else {
        kernel_address1 =  (sc_lv<4>) ("XXXX");
    }
}

void conv2D_conv2D::thread_kernel_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0)))) {
        kernel_ce0 = ap_const_logic_1;
    } else {
        kernel_ce0 = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_kernel_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)))) {
        kernel_ce1 = ap_const_logic_1;
    } else {
        kernel_ce1 = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<4>) (tmp_14_cast_fu_592_p1.read());
}

void conv2D_conv2D::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_output_r_d0() {
    output_r_d0 = (!tmp4_reg_937.read().is_01() || !tmp1_fu_596_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp4_reg_937.read()) + sc_biguint<32>(tmp1_fu_596_p2.read()));
}

void conv2D_conv2D::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_651_pp0_iter2_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv2D_conv2D::thread_p_shl1_cast_fu_475_p1() {
    p_shl1_cast_fu_475_p1 = esl_zext<6,4>(tmp_2_fu_468_p3.read());
}

void conv2D_conv2D::thread_p_shl3_cast1_fu_403_p1() {
    p_shl3_cast1_fu_403_p1 = esl_zext<6,4>(tmp_fu_396_p3.read());
}

void conv2D_conv2D::thread_p_shl3_cast_fu_407_p1() {
    p_shl3_cast_fu_407_p1 = esl_zext<5,4>(tmp_fu_396_p3.read());
}

void conv2D_conv2D::thread_p_shl_cast_fu_346_p1() {
    p_shl_cast_fu_346_p1 = esl_zext<6,5>(tmp_8_fu_339_p3.read());
}

void conv2D_conv2D::thread_tmp1_fu_596_p2() {
    tmp1_fu_596_p2 = (!tmp3_reg_932.read().is_01() || !tmp2_reg_922.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp3_reg_932.read()) + sc_biguint<32>(tmp2_reg_922.read()));
}

void conv2D_conv2D::thread_tmp2_fu_575_p2() {
    tmp2_fu_575_p2 = (!tmp_1_reg_887.read().is_01() || !tmp_1_0_1_reg_897.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_1_reg_887.read()) + sc_biguint<32>(tmp_1_0_1_reg_897.read()));
}

void conv2D_conv2D::thread_tmp3_fu_579_p2() {
    tmp3_fu_579_p2 = (!tmp_1_0_2_reg_902.read().is_01() || !tmp_1_1_reg_912.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_1_0_2_reg_902.read()) + sc_biguint<32>(tmp_1_1_reg_912.read()));
}

void conv2D_conv2D::thread_tmp4_fu_587_p2() {
    tmp4_fu_587_p2 = (!tmp6_reg_907.read().is_01() || !tmp5_fu_583_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp6_reg_907.read()) + sc_biguint<32>(tmp5_fu_583_p2.read()));
}

void conv2D_conv2D::thread_tmp5_fu_583_p2() {
    tmp5_fu_583_p2 = (!tmp_1_1_1_reg_917.read().is_01() || !tmp_1_1_2_reg_927.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_1_1_1_reg_917.read()) + sc_biguint<32>(tmp_1_1_2_reg_927.read()));
}

void conv2D_conv2D::thread_tmp6_fu_570_p2() {
    tmp6_fu_570_p2 = (!tmp7_fu_566_p2.read().is_01() || !tmp_1_2_reg_877.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp7_fu_566_p2.read()) + sc_biguint<32>(tmp_1_2_reg_877.read()));
}

void conv2D_conv2D::thread_tmp7_fu_566_p2() {
    tmp7_fu_566_p2 = (!tmp_1_2_1_reg_882.read().is_01() || !tmp_1_2_2_reg_892.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_1_2_1_reg_882.read()) + sc_biguint<32>(tmp_1_2_2_reg_892.read()));
}

void conv2D_conv2D::thread_tmp_10_fu_439_p2() {
    tmp_10_fu_439_p2 = (!tmp_9_cast8_fu_426_p1.read().is_01() || !tmp_5_fu_417_p2.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_9_cast8_fu_426_p1.read()) + sc_biguint<5>(tmp_5_fu_417_p2.read()));
}

void conv2D_conv2D::thread_tmp_11_cast_fu_434_p1() {
    tmp_11_cast_fu_434_p1 = esl_zext<64,6>(tmp_4_fu_429_p2.read());
}

void conv2D_conv2D::thread_tmp_11_fu_490_p2() {
    tmp_11_fu_490_p2 = (!tmp_9_0_1_cast_reg_709.read().is_01() || !tmp_3_reg_730.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_0_1_cast_reg_709.read()) + sc_biguint<6>(tmp_3_reg_730.read()));
}

void conv2D_conv2D::thread_tmp_12_cast_fu_526_p1() {
    tmp_12_cast_fu_526_p1 = esl_zext<64,6>(tmp_6_reg_777.read());
}

void conv2D_conv2D::thread_tmp_12_fu_499_p2() {
    tmp_12_fu_499_p2 = (!tmp_9_0_1_cast_reg_709.read().is_01() || !tmp_7_fu_479_p2.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_0_1_cast_reg_709.read()) + sc_biguint<6>(tmp_7_fu_479_p2.read()));
}

void conv2D_conv2D::thread_tmp_13_cast_fu_365_p1() {
    tmp_13_cast_fu_365_p1 = esl_zext<64,6>(tmp_9_fu_359_p2.read());
}

void conv2D_conv2D::thread_tmp_13_fu_379_p2() {
    tmp_13_fu_379_p2 = (!tmp_9_0_1_cast_fu_375_p1.read().is_01() || !tmp_s_fu_350_p2.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_0_1_cast_fu_375_p1.read()) + sc_biguint<6>(tmp_s_fu_350_p2.read()));
}

void conv2D_conv2D::thread_tmp_14_cast_fu_592_p1() {
    tmp_14_cast_fu_592_p1 = esl_zext<64,5>(tmp_10_reg_741_pp0_iter1_reg.read());
}

void conv2D_conv2D::thread_tmp_14_fu_504_p2() {
    tmp_14_fu_504_p2 = (!tmp_9_0_2_cast_reg_751.read().is_01() || !tmp_3_reg_730.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_0_2_cast_reg_751.read()) + sc_biguint<6>(tmp_3_reg_730.read()));
}

void conv2D_conv2D::thread_tmp_15_cast_fu_494_p1() {
    tmp_15_cast_fu_494_p1 = esl_zext<64,6>(tmp_11_fu_490_p2.read());
}

void conv2D_conv2D::thread_tmp_15_fu_513_p2() {
    tmp_15_fu_513_p2 = (!tmp_9_0_2_cast_reg_751.read().is_01() || !tmp_7_fu_479_p2.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_0_2_cast_reg_751.read()) + sc_biguint<6>(tmp_7_fu_479_p2.read()));
}

void conv2D_conv2D::thread_tmp_16_cast_fu_534_p1() {
    tmp_16_cast_fu_534_p1 = esl_zext<64,6>(tmp_12_reg_792.read());
}

void conv2D_conv2D::thread_tmp_16_fu_455_p2() {
    tmp_16_fu_455_p2 = (!tmp_9_0_2_cast_fu_451_p1.read().is_01() || !tmp_s_reg_688.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_0_2_cast_fu_451_p1.read()) + sc_biguint<6>(tmp_s_reg_688.read()));
}

void conv2D_conv2D::thread_tmp_17_cast_fu_385_p1() {
    tmp_17_cast_fu_385_p1 = esl_zext<64,6>(tmp_13_fu_379_p2.read());
}

void conv2D_conv2D::thread_tmp_18_cast_fu_508_p1() {
    tmp_18_cast_fu_508_p1 = esl_zext<64,6>(tmp_14_fu_504_p2.read());
}

void conv2D_conv2D::thread_tmp_19_cast_fu_546_p1() {
    tmp_19_cast_fu_546_p1 = esl_zext<64,6>(tmp_15_reg_807.read());
}

void conv2D_conv2D::thread_tmp_20_cast_fu_460_p1() {
    tmp_20_cast_fu_460_p1 = esl_zext<64,6>(tmp_16_fu_455_p2.read());
}

void conv2D_conv2D::thread_tmp_2_fu_468_p3() {
    tmp_2_fu_468_p3 = esl_concat<2,2>(tmp_5_1_mid2_reg_676.read(), ap_const_lv2_0);
}

void conv2D_conv2D::thread_tmp_3_fu_411_p2() {
    tmp_3_fu_411_p2 = (!p_shl3_cast1_fu_403_p1.read().is_01() || !tmp_mid2_cast1_fu_390_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(p_shl3_cast1_fu_403_p1.read()) + sc_biguint<6>(tmp_mid2_cast1_fu_390_p1.read()));
}

void conv2D_conv2D::thread_tmp_4_fu_429_p2() {
    tmp_4_fu_429_p2 = (!tmp_9_cast_reg_693.read().is_01() || !tmp_3_fu_411_p2.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_cast_reg_693.read()) + sc_biguint<6>(tmp_3_fu_411_p2.read()));
}

void conv2D_conv2D::thread_tmp_5_1_mid2_cast9_fu_465_p1() {
    tmp_5_1_mid2_cast9_fu_465_p1 = esl_zext<6,2>(tmp_5_1_mid2_reg_676.read());
}

void conv2D_conv2D::thread_tmp_5_1_mid2_fu_318_p3() {
    tmp_5_1_mid2_fu_318_p3 = (!exitcond_fu_290_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_fu_290_p2.read()[0].to_bool())? i_1_mid1_fu_312_p2.read(): i_1_fu_272_p2.read());
}

void conv2D_conv2D::thread_tmp_5_2_mid2_cast_fu_336_p1() {
    tmp_5_2_mid2_cast_fu_336_p1 = esl_zext<6,3>(tmp_5_2_mid2_v_reg_682.read());
}

void conv2D_conv2D::thread_tmp_5_2_mid2_v_fu_330_p2() {
    tmp_5_2_mid2_v_fu_330_p2 = (!tmp_5_2_mid2_v_v_fu_326_p1.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<3>(): (sc_biguint<3>(tmp_5_2_mid2_v_v_fu_326_p1.read()) + sc_biguint<3>(ap_const_lv3_2));
}

void conv2D_conv2D::thread_tmp_5_2_mid2_v_v_fu_326_p1() {
    tmp_5_2_mid2_v_v_fu_326_p1 = esl_zext<3,2>(tmp_mid2_fu_304_p3.read());
}

void conv2D_conv2D::thread_tmp_5_fu_417_p2() {
    tmp_5_fu_417_p2 = (!p_shl3_cast_fu_407_p1.read().is_01() || !tmp_mid2_cast_fu_393_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl3_cast_fu_407_p1.read()) - sc_biguint<5>(tmp_mid2_cast_fu_393_p1.read()));
}

void conv2D_conv2D::thread_tmp_6_fu_485_p2() {
    tmp_6_fu_485_p2 = (!tmp_9_cast_reg_693.read().is_01() || !tmp_7_fu_479_p2.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_cast_reg_693.read()) + sc_biguint<6>(tmp_7_fu_479_p2.read()));
}

void conv2D_conv2D::thread_tmp_7_fu_479_p2() {
    tmp_7_fu_479_p2 = (!p_shl1_cast_fu_475_p1.read().is_01() || !tmp_5_1_mid2_cast9_fu_465_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(p_shl1_cast_fu_475_p1.read()) + sc_biguint<6>(tmp_5_1_mid2_cast9_fu_465_p1.read()));
}

void conv2D_conv2D::thread_tmp_8_0_2_fu_445_p2() {
    tmp_8_0_2_fu_445_p2 = (!j_cast_fu_423_p1.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<3>(): (sc_biguint<3>(j_cast_fu_423_p1.read()) + sc_biguint<3>(ap_const_lv3_2));
}

void conv2D_conv2D::thread_tmp_8_fu_339_p3() {
    tmp_8_fu_339_p3 = esl_concat<3,2>(tmp_5_2_mid2_v_reg_682.read(), ap_const_lv2_0);
}

void conv2D_conv2D::thread_tmp_9_0_1_cast_fu_375_p1() {
    tmp_9_0_1_cast_fu_375_p1 = esl_zext<6,2>(j_1_fu_370_p2.read());
}

void conv2D_conv2D::thread_tmp_9_0_2_cast_fu_451_p1() {
    tmp_9_0_2_cast_fu_451_p1 = esl_zext<6,3>(tmp_8_0_2_fu_445_p2.read());
}

void conv2D_conv2D::thread_tmp_9_cast8_fu_426_p1() {
    tmp_9_cast8_fu_426_p1 = esl_zext<5,2>(j_mid2_reg_660.read());
}

void conv2D_conv2D::thread_tmp_9_cast_fu_356_p1() {
    tmp_9_cast_fu_356_p1 = esl_zext<6,2>(j_mid2_reg_660.read());
}

void conv2D_conv2D::thread_tmp_9_fu_359_p2() {
    tmp_9_fu_359_p2 = (!tmp_9_cast_fu_356_p1.read().is_01() || !tmp_s_fu_350_p2.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_cast_fu_356_p1.read()) + sc_biguint<6>(tmp_s_fu_350_p2.read()));
}

void conv2D_conv2D::thread_tmp_fu_396_p3() {
    tmp_fu_396_p3 = esl_concat<2,2>(tmp_mid2_reg_668.read(), ap_const_lv2_0);
}

void conv2D_conv2D::thread_tmp_mid2_cast1_fu_390_p1() {
    tmp_mid2_cast1_fu_390_p1 = esl_zext<6,2>(tmp_mid2_reg_668.read());
}

void conv2D_conv2D::thread_tmp_mid2_cast_fu_393_p1() {
    tmp_mid2_cast_fu_393_p1 = esl_zext<5,2>(tmp_mid2_reg_668.read());
}

void conv2D_conv2D::thread_tmp_mid2_fu_304_p3() {
    tmp_mid2_fu_304_p3 = (!exitcond_fu_290_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_fu_290_p2.read()[0].to_bool())? i_1_fu_272_p2.read(): ap_phi_mux_i_phi_fu_254_p4.read());
}

void conv2D_conv2D::thread_tmp_s_fu_350_p2() {
    tmp_s_fu_350_p2 = (!p_shl_cast_fu_346_p1.read().is_01() || !tmp_5_2_mid2_cast_fu_336_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(p_shl_cast_fu_346_p1.read()) + sc_biguint<6>(tmp_5_2_mid2_cast_fu_336_p1.read()));
}

void conv2D_conv2D::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_278_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_278_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 32 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

void conv2D_conv2D::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_address0\" :  \"" << input_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_ce0\" :  \"" << input_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_q0\" :  \"" << input_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_address1\" :  \"" << input_r_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_ce1\" :  \"" << input_r_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_q1\" :  \"" << input_r_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_address0\" :  \"" << kernel_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_ce0\" :  \"" << kernel_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"kernel_q0\" :  \"" << kernel_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_address1\" :  \"" << kernel_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_ce1\" :  \"" << kernel_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"kernel_q1\" :  \"" << kernel_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_address0\" :  \"" << output_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_ce0\" :  \"" << output_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_we0\" :  \"" << output_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_d0\" :  \"" << output_r_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

